name: test

on:
  push:
  pull_request:

jobs:
  test:
    name: nvim ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.version }}
      - name: Run tests
        run: nvim --clean -l tests/run.lua
